mcp:
  client:
    # 火山引擎API配置
    volcano:
      # API密钥信息
      apiKey: 55ff613b-04fa-4e11-a149-ddf5a12013c9
      # 服务接口配置
      deepseek:
        endpoint: https://ark.cn-beijing.volces.com/api/v3/chat/completions
        model: deepseek-v3-250324
      # 请求配置
      request:
        timeout: 43200
        retries: 3
    
    # MCP服务配置
    server:
      url: http://localhost:9509
      path: api/chat
      # 设置为true启用MCP协议
      useMcpProtocol: true
      
# 日志配置
logging:
  level:
    root: INFO
    com.example.mcp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 